
const ACTIONS = {
    GET_ALL_CUSTOMERS: "GET_ALL_CUSTOMERS",
    PATCH_CUSTOMER: "PATCH_CUSTOMER",
    DELETE_CUSTOMER: "DELETE_CUSTOMER",
    ADD_CUSTOMER: "ADD_CUSTOMER"
};

export default ACTIONS;