
const ACTIONS = {
    GET_RENTAL_AGREEMENTS: "GET_RENTAL_AGREEMENTS",
    UPDATE_RENTAL_AGREEMENTS: "UPDATE_RENTAL_AGREEMENTS",
    DELETE_RENTAL_AGREEMENTS: "DELETE_RENTAL_AGREEMENTS",
    ADD_RENTAL_AGREEMENT: "ADD_RENTAL_AGREEMENT",
    CLOSE_RENTAL_AGREEMENT: "CLOSE_RENTAL_AGREEMENT",
    ADD_RENTAL_AGREEMENT_PDF: "ADD_RENTAL_AGREEMENT_PDF"
};

export default ACTIONS;