
const ACTIONS = {
    GET_STATIC_PAGES: "GET_STATIC_PAGES",
    ADD_STATIC_PAGE: "ADD_STATIC_PAGE",
    UPDATE_STATIC_PAGE: "UPDATE_STATIC_PAGE",
    DELETE_STATIC_PAGE: "DELETE_STATIC_PAGE"
};

export default ACTIONS;