const ACTIONS = {
    PATCH_PRODUCT_PROP: "PATCH_PRODUCT_PROP",
    ADD_PRODUCT_PROP: "ADD_PRODUCT_PROP",
    UPDATE_PRODUCT_PROP: "UPDATE_PRODUCT_PROP",
    DELETE_PRODUCT_PROP: "DELETE_PRODUCT_PROP"
};

export default ACTIONS;