const ACTIONS = {
    ADD_SCHEDULED_SERVICE: "ADD_SCHEDULED_SERVICE",
    UPDATE_SCHEDULED_SERVICE: "UPDATE_SCHEDULED_SERVICE",
    DELETE_SCHEDULED_SERVICE: "DELETE_SCHEDULED_SERVICE",
    PATCH_SCHEDULED_SERVICE: "PATCH_SCHEDULED_SERVICE"
};

export default ACTIONS;