const ACTIONS = {
    ADD_SPARE_PART: "ADD_SPARE_PART",
    UPDATE_SPARE_PART: "UPDATE_SPARE_PART",
    DELETE_SPARE_PART: "DELETE_SPARE_PART",
    PATCH_SPARE_PART_PROP: "PATCH_SPARE_PART_PROP"
};

export default ACTIONS;