const ACTIONS = {
    ADD_DIAGRAM: "ADD_DIAGRAM",
    UPDATE_DIAGRAM: "UPDATE_DIAGRAM",
    DELETE_DIAGRAM: "DELETE_DIAGRAM",
    PATCH_DIAGRAM: "PATCH_DIAGRAM",
    GET_DIAGRAMS: "GET_DIAGRAMS"
};

export default ACTIONS;